version: "3.0"
services:
  gunbot:
    build: .
    container_name: gunbot
    restart: always
    ports:
      - 5555:5000
    environment:
      - TZ=Australia/Perth
      - PGID=100
      - PUID=1026
    volumes:
      - "/volume2/docker/gunbot/config/backups:/gunbot/backups"
      - "/volume2/docker/gunbot/config/logs:/gunbot/gunbot_logs"
      - "/volume2/docker/gunbot/config/config.js:/gunbot/config.js"
      - "/volume2/docker/gunbot/config/autoconfig.json:/gunbot/autoconfig.json"

    networks:
      macvlan:
        ipv4_address: 10.1.1.10
    
networks:
  macvlan:
    external: true
      
